config/routes.rb
Diplomatiki::Application.routes.draw do
  resources :exercises do
      collection do
           get 'myexercises'
      end
  end

	devise_for :users, :controllers => { :registrations => "users/registrations" }

	match '/auth/:provider/callback' => 'services#create'
	match '/auth/twitter', :as => :auth_twitter

	resources :writings

	resources :services, :only => [:index, :create, :destroy]

	resources :admin, :only => [:index, :delete] do
		member do
			get 'editreject'
			put 'reject'
			put 'accept'
			put 'accept1'
		end
		collection do
			get 'questions'
			get 'users'
		end
	end

	resources :users

	resources :questions do
		collection do
			get 'autocomplete_tag_name'
			get 'all'
			get 'myquestions'
			get 'about'
			delete 'destroy'
		end

		member do
			put 'submit'
			get 'postfacebook'
		end

		resources :comments, :only => [:create, :destroy]
		resources :ratings, :only => [:create, :update, :destroy]
	end

	root :to => 'questions#index'
end

app/models/question.rb
class Question < ActiveRecord::Base
  acts_as_taggable_on :tags
  belongs_to :user
  has_many :comments, :dependent => :destroy
  has_many :ratings, :dependent => :destroy

  attr_accessible :title, :body, :tag_list

  validates :user_id, :presence => true
  validates :title, :presence => true, :length => { :maximum => 80 }
  validates :body, :presence => true
  validates :message, :length => { :maximum => 5000 }
  validates :state, :presence => true, :numericality => true, :inclusion => { :in => 0..4 }


  # returns the number of ratings for that question
  def count_ratings
    self.ratings.all.count
  end

  # returns the average rating for that question
  def avg_rating
    @avg = self.ratings.average(:stars)
    @avg ? @avg : 0
  end

  def self.search(search)
  if search
    where('title LIKE ? or body LIKE ?', "%#{search}%", "%#{search}%")
  else
    scoped
  end
end
end

app/controllers/questions_controller.rb
# encoding: utf-8
class QuestionsController < ApplicationController
	respond_to :json
	autocomplete :tag, :name
	# μόνο οι μέθοδοι index, και all είναι προσβάσιμες από μη πιστοποιημένους χρήστες
	before_filter :authenticate_user!, :except => [:index, :all]
	rescue_from ActiveRecord::RecordNotFound, :with => :record_not_found


	def tag_cloud
		@tags ||= Question.tag_counts_on(:tags)
	end


	def index
		options = {} # εδώ οποιαδήποτε συνθήκη search/pagination
		@tags = Question.tag_counts_on(:tags).limit(8).order('count desc')
		klass = Question
		klass = klass.tagged_with(@tag) if (@tag = params[:tag]).present?
		@questions = klass.where(:state => '4').paginate(:page => params[:page])
		#@questions = Question.where(:state => '4').paginate(:page => params[:page], :per_page => 10)
		respond_to do |format|
			format.html  # index.html.erb
			format.xml  { render :xml => @questions }
		end
	end


	def all
		options = {} # εδώ οποιαδήποτε συνθήκη search/pagination
		@tags = Question.tag_counts_on(:tags)
		klass = Question
		klass = klass.tagged_with(@tag) if (@tag = params[:tag]).present?
		@questions = klass.where(:state => ['3', '4']).search(params[:search]).order('accepted desc').paginate(:page => params[:page], :per_page => 10)
		#@questions = Question.where(:state => ['3', '4']).search(params[:search]).order('accepted desc').paginate(:page => params[:page], :per_page => 10)
		respond_to do |format|
			format.html { render 'index' }
			format.xml  { render :xml => @questions }
		end
	end


	def myquestions
		@myquestions = current_user.questions.all
		respond_to do |format|
			format.html { render 'myquestions'}
			format.xml  { render :xml => @myquestions }
		end
	end


	def auto_complete_for_link_tag_list
		@tags = Link.tag_counts_on(:tags).where('tags.name LIKE ?', params[:link][:tag_list])
		render :inline => "<%= auto_complete_result(@tags, 'name') %>", :layout => false
		logger.info "#{@tags.size} tags found."
	end


	def submit
		@question = current_user.questions.find(params[:id])
		# submit μόνο αν η ερώτηση είναι σε κατάσταση "πρόχειρη" ή "μη αποδεκτή"
		if (@question.state == 0) or (@question.state == 2)
			@question.state = 1
			@question.submitted = Time.now
			if @question.save
				flash[:notice] = 'Η ερώτησή σας υποβλήθηκε με επιτυχία για έγκριση.'
			else
				flash[:error] = 'Υπάρχει ένα σφάλμα κατά την υποβολή της ερώτησης.'
			end
		else
			flash[:error] = 'Η ερώτηση δεν μπορεί να υποβληθεί.'
		end
		respond_to do |format|
			format.html { redirect_to(:action => 'myquestions') }
			format.xml  { head :ok }
		end
	end


	def show
		@question = Question.find(params[:id])
		@comments = @question.comments.all
		#@name = Lesson.find(params[:id])
		if user_signed_in?
			#@name = current_user.lesson.name
			@rating_currentuser = @question.ratings.find_by_user_id(current_user.id)
			unless @rating_currentuser
				@rating_currentuser = current_user.ratings.new
			end
		end
		respond_to do |format|
			format.html # show.html.erb
			format.xml  { render :xml => @question }
		end
	end


	def new
		@question = current_user.questions.new
		respond_to do |format|
			format.html # new.html.erb
			format.xml  { render :xml => @question }
		end
	end


	def postfacebook
		@question = current_user.questions.find(params[:id])
		begin
			current_user.facebook.feed!(
			:message => "Στο σχολείο μετά το σχολείο δημοσιεύθηκε ερώτηση με τίτλο: #{ @question.title }",
			:name => 'My Rails 3 App with Omniauth, Devise and FB_graph')
			page = FbGraph::Page.new(163573307071006, :access_token => current_user.services.find_by_provider('facebook').token)
			page.feed!(
			:message => "Στο σχολείο μετά το σχολείο δημοσιεύθηκε ερώτηση με τίτλο: #{ @question.title }",
			:name => 'My Rails 3 App with Omniauth, Devise and FB_graph')
		rescue FbGraph::InvalidToken => e
			case e.message
			when /Error validating access token/
				flash[:alert] = "Σφάλμα επικύρωσης. Θα χρειαστεί εκ νέου αυθεντικοποίηση!"
				respond_to do |format|
					format.html { redirect_to(@question) }
					format.xml  { head :ok }
				end
			when /Duplicate status message/
				flash[:alert] = "Η ερώτηση έχει ήδη δημοσιευθεί στο Facebook!"
				respond_to do |format|
					format.html { redirect_to(@question) }
					format.xml  { head :ok }
				end
			end
		rescue FbGraph::InvalidRequest => e
			case e.message
			when /OAuthException :: Error validating access token/
				flash[:alert] = "Σφάλμα επικύρωσης. Θα χρειαστεί εκ νέου αυθεντικοποίηση!"
				respond_to do |format|
					format.html { redirect_to(@question) }
					format.xml  { head :ok }
				end
			when /Duplicate status message/
				flash[:alert] = "Η ερώτηση έχει ήδη δημοσιευθεί στο Facebook!"
				respond_to do |format|
					format.html { redirect_to(@question) }
					format.xml  { head :ok }
				end
			end
		else
			respond_to do |format|
				format.html { redirect_to( @question, :notice => 'Ο τίτλος της ερώτησης δημοσιεύθηκε με επιτυχία στο Facebook!') }
				format.xml  { head :ok }
			end
		end
	end


	def edit
		@question = current_user.questions.find(params[:id])
	end


	def create
		@question = current_user.questions.new(params[:question])
		respond_to do |format|
			if @question.save
				format.html { redirect_to(@question, :notice => 'Η ερώτηση δημιουργήθηκε επιτυχώς.') }
				format.xml  { render :xml => @question, :status => :created, :location => @question }
			else
				format.html { render :action => "new" }
				format.xml  { render :xml => @question.errors, :status => :unprocessable_entity }
			end
		end
	end


	def update
		@question = current_user.questions.find(params[:id])
		# Εάν μία ερώτηση έχει ήδη γίνει αποδεκτή ο φοιτητής δεν επιτρέπεται να κάνει αλλαγές στον τίτλο
		if @question.state > 2
			params[:question].delete(:title)
		end
		respond_to do |format|
			if @question.update_attributes(params[:question])
				format.html { redirect_to(@question, :notice => 'Η ερώτηση ενημερώθηκε επιτυχώς.') }
				format.xml  { head :ok }
			else
				format.html { render :action => "edit" }
				format.xml  { render :xml => @question.errors, :status => :unprocessable_entity }
			end
		end
	end


	def destroy
		# οι καθηγητές μπορούν να διαγράψουν ερωτήσεις σε κάθε κατάσταση
		@question = Question.find(params[:id])
		if current_user.user_kind == 1
			@question.destroy
		else
			@question = current_user.questions.find(params[:id])
			# Ο φοιτητής μπορεί να διαγράψει μόνο ερωτήσεις σε κατάσταση "πρόχειρη", "προς υποβολή" ή "μη αποδεκτή"
			if (@question.state < 3)
				@question.destroy
			else
				flash[:error] = 'Η ερώτηση δεν μπορεί να διαγραφεί.'
			end
		end
		respond_to do |format|
			format.html { redirect_to(questions_url) }
			format.xml  { head :ok }
		end
	end


	protected
	def record_not_found
		flash[:error] = 'Η ερώτηση που ζητήσατε δεν βρέθηκε.'
		redirect_to root_url
	end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "σφάλμα") %> και έτσι δεν επιτρέπεται η αποθήκευση της ερώτησης</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <% # Ο τίτλος του άρθρου δεν μπορεί να αλλάξει εφόσον το άρθρο γίνει αποδεκτό %>
  <% if @question.state < 3 %>
    <div class="field">
        <label for="question_title">Τίτλος (Κείμενο, μέγιστος αριθμός χαρακτήρων 80)</label><br />
        <%= f.text_field :title, :size => "100%", :class => "fullwidth"  %>
    </div>
   <% else %>
    <div class="field">
        <label for="question_title">Τίτλος (Δεν μπορεί να αλλάξει εφόσον η ερώτηση έχει γίνει αποδεκτή)</label><br />
        <%= f.text_field :title, :readonly => true,  :size => "100%", :class => "fullwidth"  %>
    </div>
   <% end %>

  <div class="field">
    <label for="question_body">Η ερώτησή σας (Μετατρέψτε το απλό κείμενο σε html - <%= link_to "Περισσότερα εδώ!", 'http://redcloth.org' %>)</label><br />
    <%= f.text_area :body, :size => "100%x15", :class => "fullwidth"  %>
  </div>

  <div class="field">
   <label for="tag_list">Κατηγορία (Μπορείτε να προσθέσετε διαφορετικές κατηγορίες διαχωρίζοντάς τες με κόμμα)</label><br />
    <%= f.autocomplete_field :tag_list, autocomplete_tag_name_questions_path, :"data-delimiter" => ', ' %>
  </div>

   <div class="actions">
    <%= f.submit "Δημιουργία ερώτησης", :class => "awesome custom red" %>
    <%= link_to 'Εμφάνιση αυτής της ερώτησης', @question, :class => "awesome custom red" %>
    <%= link_to 'Επιστροφή στις ερωτήσεις μου', myquestions_questions_path, :class => "awesome custom red" %>
  </div>

<% end %>

app/views/questions/about.html.erb
<h1>Χώρος Συζήτησης Ενημέρωσης</h1>

<p>Οδηγός χρήσης</p>

Στο "σχολείο μετά το σχολείο" μπορείτε
να δημιουργήσετε λογαριασμό και να συνδεθείτε με
τους κωδικούς που θα επιλέξετε, αρκεί να έχετε ένα
έγκυρο λογαριασμό ηλεκτρονικού ταχυδρομείου.

Εναλλακτικά μπορείτε να έχετε πρόσβαση με μια από
τις ακόλουθες υπηρεσίες κοινωνικής δικτύωσης:</p>
<p>Facebook</p>
<p>Twitter</p>
<p>Google+</p>
<p>LinkedIn</p>
<p>Yahoo</p>
<p>Github</p>
<p> Για να δημοσιεύσετε μια νέα ερώτηση, αφού κάνετε λογαριασμό και
 μπορείτε πλέον να συνδεθείτε, θα πρέπει πρώτα να ενημερώσετε τα στοιχεία σας
 στο <p>Προφίλ μου</p> και στην συνέχεια να πάτε στην ενότητα</p>
<p>Ερωτήσεις</p>
και έπειτα στο</p> <p>Δημιουργία νέας ερώτησης.</p> Για λόγους ποιότητας
της αρχικής δημοσίευσης η αρχική σας ερώτηση θα ελεγχθεί από
τον υπεύθυνο διδάσκοντα για την θεματική σας ενότητα.
Ωστόσο εσείς είστε ο κύριος υπεύθυνος της ανάρτησης αφού μετά την
αποδοχή της ερώτησης από τον διαχειριστή μπορείτε να την αλλάξετε. Μόνο
ο τίτλος της ερώτησης δεν μπορεί να αλλάξει.
Μπορείτε επίσης να σχολιάσετε ή να βαθμολογήσετε ερωτήσεις συμφοιτητών σας.</p>
Στην ενότητα</p> <p> Δικτύωση </p> μπορείτε να συνδέσετε και άλλους λογαριασμούς
στο προφίλ σας, ούτως ώστε να συνδέεστε στον χώρο συζήτησης ενημέρωσης με την
βοήθεια του λογαριασμού σας σε κάποιο κοινωνικό δίκτυο.

app/views/questions/edit.html.erb
<section id="myquestions">
    <h2>Επεξεργασία ερώτησης&nbsp;&nbsp;&nbsp;<%= link_to '(Εμφάνιση αυτής της ερώτησης)', @question %></h2>

    <%= render 'form' %>
</section>

app/views/questions/index.html.erb
<section id = "questions">
    <% @questions.each do |question| %>
        <question class="question">
            <ul class="stars floatstars">
                <li class="yellowstars" style="width: <%= question.avg_rating * 25 %>px !important;"></li>
            </ul>
            <div class = "title"><%= link_to question.title, question %></div>
            <div class = "byline"><%= l(question.created_at, :format => '%d %B, %Y') %> : <%= question.state %></div>

        </question>
    <% end %>

     <div class='pagination'>
        <%= will_paginate @questions %>
    </div>

     <div class='tag-box'>
       <% @tags.sort_by(&:count).reverse.each do |k| %>

      <% url_opts = {:action => "all", :controller => "questions"}
         link_name = "#{k.name} (#{k.count})" %>
      <% if @tag == k.name %>
        <%= link_to link_name, url_opts.merge(:tag => nil), :class => "tag current_tag", :title => "Κλικ για εμφάνιση όλων" %>
      <% else %>
        <%= link_to link_name,  url_opts.merge(:tag => k.name), :class => "tag", :title => "Κλικ για εμφάνιση των ερωτήσεων στην κατηγορία #{k.name}" %>
      <% end %>
    <% end %>
    </div>
</section>

app/views/questions/myquestions.html.erb
# encoding: utf-8
<h2>Διαχείριση των ερωτήσεων</h2>

<p><%= link_to 'Δημιουργία νέας ερώτησης', new_question_path, :class => "awesome custom red" %></p>

<section id="myquestions">

    <% if !@myquestions.empty? %>

        <% @myquestions.each do |question| %>

            <question class="myquestion">

                <div class="title"><%= question.title %></div>
                <div class="created">
                   <p> Δημιουργήθηκε: <%= l(question.created_at, :format => '%d %b %Y') %> </p>
                   <p>   Ενημερώθηκε: <%= l(question.updated_at, :format => '%d %b %Y') %> </p>
                </div>

                <!-- Κατάσταση ερώτησης:  0...Πρόχειρη, 1...Προς υποβολή, 2...Μη αποδεκτή, 3...Ολοκληρωμένη ερώτηση, 4...Προτεινόμενη ερώτηση -->

                <% if (question.state == 0) or (question.state == 2) %>
                 <span><%= link_to "Υποβολή τώρα", submit_question_path(question), :method => :put, :class => "awesome custom red" %>
                 </span>

                  <div class="state">Τρέχουσα κατάσταση: Πρόχειρη (Ορατό μέσω απευθείας link)</div>
                <% end%>

                <% if question.state == 1 %>
                  <div class="state">Τρέχουσα κατάσταση: Προς υποβολή (<%= l(question.submitted, :format => '%d %b %Y') %>)</div>
                <% end%>

                <% if question.state == 2 %>
                  <div class="state">Τρέχουσα κατάσταση: Μη αποδεκτή (<%= l(question.submitted, :format => '%d %b %Y') %>)</div>
                  <div class="reject">Παρακαλώ διαβάστε τα σχόλια, εξετάστε την ερώτησή σας και προσπαθήστε ξανά!</div>
                  <div class="rejectmsg"><%= question.message %></div>
                <% end%>

                <% if question.state == 3 %>
                  <div class="state">Τρέχουσα κατάσταση: Αποδοχή και δημοσίευση της ερώτησης (<%= l(question.accepted, :format => '%d %b %Y') %>)</div>
                <% end %>

                <% if question.state == 4 %>
                  <div class="state">Τρέχουσα κατάσταση: Αποδοχή και δημοσίευση της ερώτησης ως <b>Προτεινόμενη ερώτηση</b> (<%= l(question.accepted, :format => '%d %b %Y') %>)</div>
                <% end %>

                <div class="actions">
                    <span class="Προβολή"><%= link_to 'Προβολή', question, :class => "awesome custom red" %></span>
                    <span class="Επεξεργασία"><%= link_to 'Επεξεργασία', edit_question_path(question), :class => "awesome custom red" %></span>
                    <% if ((question.state == 3) or (question.state == 4) and (current_user.services.find_by_provider('facebook').token rescue nil )) %>
                    <span> <%= link_to 'Δημοσίευση στο Facebook', postfacebook_question_path(question), :class => "awesome custom blue" %></span>
                    <% end %>
                    <% if (question.state == 0) or (question.state == 2) %>
                        <span><%= link_to "Υποβολή τώρα", submit_question_path(question), :method => :put, :class => "awesome custom red" %>
                    </span>
                    <% end %>
                    <% if question.state < 3 %>
                        <span class="Διαγραφή"><%= link_to 'Διαγραφή', question, :confirm => 'Είσαι σίγουρος;', :method => :delete, :class => "awesome custom red" %></span>
                    <% end %>
                </div>

            </question>
        <% end %>

    <% else %>
        <p>Δεν έχεις γράψει ακόμη κάποια ερώτηση. Ξεκίνα τώρα: <%= link_to 'Νέα ερώτηση', new_question_path, :class => "awesome custom red" %></p>
    <% end %>

</section>

app/views/questions/new.html.erb
<section id="myquestions">
    <h2>Νέα ερώτηση</h2>

    <%= render 'form' %>

    <%= sanitize textilize ('Μια *απλή* παράγραφος με _πλάγια γραμματοσειρά_ και ένα "link":http://redcloth.org') %>
    <%= sanitize CodeRay.highlight("Εδώ οι χαρακτήρες του κειμένου είναι χρώματος λευκού σε μαύρο φόντο!", :ruby, :css => :class) %>
</section>

app/views/questions/show.html.erb
<section id="questionheader">
    <h2><%= @question.title %>
       <ul class="stars floatstars">
            <li class="yellowstars" style="width: <%= @question.avg_rating * 25 %>px !important;"></li>
            <li class="text">Ο μέσος όρος είναι <%= @question.avg_rating %> από συνολικά <%= pluralize(@question.count_ratings, "ψήφο") %></li>
       </ul>

    </h2>


    <div class="byline">Γράφτηκε από: <%= @question.user.fullname %>, Θεματική ενότητα: <%= @question.user.lesson.try(:name) %></div>
    <div class="byline">Προσωπική ιστοσελίδα: <%= link_to @question.user.weburl, url_for(@question.user.weburl) %></div>
    <div class="byline">Σύντομο βιογραφικό: <%= @question.user.shortbio %></div>


    <div class="avatar"><%= image_tag gravatar(@question.user.email, 64) %></div>

</section>

<section id="questionbody" class="textile">

	<h2><%= @question.title %></h2>
	<div class="textile">
		<%= sanitize textilize(coderay_dressed(@question.body)) %>
	</div>

</section>


<% # comments και ratings είναι διαθέσιμα μόνο για άρθρα που είναι δημοσιευμένα %>
<% if @question.state > 2 %>

     <section id="rating">
        <% if user_signed_in? %>
            <%= form_for [@question, @rating_currentuser] do |f| %>
                <div id="ratingbox">
                    <ul id="ratingbuttons">
                        <li><%= f.radio_button :stars, "5" %><span>Τέλεια</span></li>
                        <li><%= f.radio_button :stars, "4" %><span>Πολύ καλή</span></li>
                        <li><%= f.radio_button :stars, "3" %><span>Καλή</span></li>
                        <li><%= f.radio_button :stars, "2" %><span>Μέτρια</span></li>
                        <li><%= f.radio_button :stars, "1" %><span>Αδιάφορη</span></li>
                    </ul>
                    <div class="center"><%= f.submit "Αξιολόγησε αυτή την ερώτηση", :class => "awesome custom red" %></div>
                </div>
            <% end %>
        <% else %>
            <div id="ratingbox"><%= link_to "Είσοδος", new_user_session_path %> για να βαθμολογήσεις αυτό το άρθρο</div>
        <% end %>
    </section>
    <section id="comments">
        <% @comments.each do |comment| %>
            <question class="comment">
                <div class="avatar"><%= image_tag gravatar(comment.user.email, 48) %></div>
                <div class="commentbody">
                    <div class="commenthead">

                      <%= link_to comment.user.fullname, url_for(comment.user.weburl) %>, <%= comment.user.lesson.try(:name) %>, - <%=time_ago_in_words(comment.created_at)%> πριν

                      <% # εμφάνιση του link διαγραφή μόνο για σχόλια που έχουν γραφεί από τον συγκεκριμένο χρήστη %>
                      <% if user_signed_in? and comment.user_id == current_user.id %>
                          <span><%= link_to 'Διαγραφή', question_comment_path(@question, comment), :confirm => 'Are you sure?', :method => :delete, :class => "" %></span>
                      <% end %>
                    </div>
                    <div><%= comment.body %></div>
                </div>
            </question>
        <% end %>

        <% # add a new comment %>
        <question class="comment newcomment">
                <% if user_signed_in? %>
                    <div class="avatar"><%= image_tag gravatar(current_user.email, 48) %></div>
                    <div class="commentbody">
                        <% if current_user.fullname == nil or current_user.fullname == '' %>
                            <div class="commenthead">
                                Παρακαλώ ενημερώστε το <%= link_to "Προφίλ", edit_user_registration_path %> πριν σχολιάσετε το άρθρο.
                            </div>
                        <% else %>
                            <div class="commenthead">
                                <%= current_user.fullname %>
                            </div>
                            <div>
                                <%= form_for [@question, current_user.comments.new] do |f| %>
                                    <%= f.text_area :body, :size => "100%x10", :class => "fullwidth" %>
                                    <%= f.submit "Πρόσθεσε σχόλιο", :class => "awesome custom red" %>
                                <% end %>
                            </div>
                        <% end %>
                    </div>
                <% else %>
                    <div class="signin">
                       Παρακαλώ κάντε <%= link_to "Σύνδεση", new_user_session_path %> πριν σχολιάσετε κάποια ερώτηση.
                    </div>
                <% end %>
        </question>
    </section>
<% end %>