config/routes.rb
Diplomatiki::Application.routes.draw do
  resources :exercises do
      collection do
           get 'myexercises'
      end
  end

	devise_for :users, :controllers => { :registrations => "users/registrations" }

	match '/auth/:provider/callback' => 'services#create'
	match '/auth/twitter', :as => :auth_twitter

	resources :writings

	resources :services, :only => [:index, :create, :destroy]

	resources :admin, :only => [:index, :delete] do
		member do
			get 'editreject'
			put 'reject'
			put 'accept'
			put 'accept1'
		end
		collection do
			get 'questions'
			get 'users'
		end
	end

	resources :users

	resources :questions do
		collection do
			get 'autocomplete_tag_name'
			get 'all'
			get 'myquestions'
			get 'about'
			delete 'destroy'
		end

		member do
			put 'submit'
			get 'postfacebook'
		end

		resources :comments, :only => [:create, :destroy]
		resources :ratings, :only => [:create, :update, :destroy]
	end

	root :to => 'questions#index'
end

app/views/admin/articles.html.erb
<section id = "admin">
<%= javascript_include_tag :defaults %>
<h2>Διαχειριστής: <%= @state_name.capitalize %> Άρθρο</h2>

    <% @articles.each do |article| %>
      <p>
        <h4><%= link_to article.title, article %></h4>
        Δημιουργός: <%= article.student.fullname %>

        <%= link_to 'Διαγραφή', article, :confirm => 'Προσοχή! Αυτή η ενέργεια θα διαγράψει οριστικά το άρθρο. Να γίνει η διαγραφή;', :method => :delete %>

        <% if article.state == 1 %>
          <%= link_to 'Απόρριψη', editreject_admin_path(article) %>
          <%= link_to 'Όλα τα άρθρα', accept_admin_path(article, :value => '0'), :method => :put %>
          <%= link_to 'Προτεινόμενα άρθρα', accept_admin_path(article, :value => '1'), :method => :put %>
        <% end %>
      </p>
    <% end %>
</section>

app/views/admin/edit.html.erb
<h1>User <%= @user.id -%></h1>

<h2>Ασκήσεις χρήστη</h2>
<% form_for @user do -%>
  <% Exercise.all.each do |exercise| -%>
    <div>
      <%= check_box_tag :exercise_ids, exercise.id, @user.exercises.include?(exercise), :name => 'user[exercise_ids][]' -%>
      <%= label_tag :exercise_ids, exercise.id -%>
    </div>
  <% end -%>
  <%= submit_tag -%>
<% end -%>

app/views/admin/editreject.html.erb
<section id = "admin">
    <h4><%= link_to @question.title, @question %></h4>
    Δημιουργός: <%= @question.user.fullname %><br />

    <br /><br /><br />

    <%= form_for(@question, :url => reject_admin_path(@question)) do |f| %>
          <% if @question.errors.any? %>
                <div id="error_explanation">
                    <h2><%= pluralize(@question.errors.count, "λάθος δεν επιτρέπει") %> την αποθήκευση του άρθρου</h2>
                    <ul>
                        <% @question.errors.full_messages.each do |msg| %>
                            <li><%= msg %></li>
                        <% end %>
                    </ul>
                </div>
          <% end %>

          <div class="field">
                <label for="question_message">Μήνυμα προς τον δημιουργό του άρθρου</label><br />
                <%= f.text_area :message, :size => "100%x10", :class => "fullwidth"  %>
          </div>

          <div class="actions">
                <%= f.submit "Απόρριψη άρθρου", :class => "awesome custom red" %>
          </div>
    <% end %>
</section>

app/views/admin/index.html.erb
# encoding: utf-8
<section id = "admin">
    <h2>Διαχειριστής: Πίνακας ελέγχου</h2>
    <h3>Ασκήσεις</h3>
    <p>
        Στατιστικά:  </p>
        <p>
        <%= link_to pluralize(@num_state5, "Άσκηση"), exercises_path %>
         </p>

<h3>Προγραμματισμός ύλης</h3>

    <%= link_to "Ημερομηνία παράδοσης άσκησης", new_writing_path, :method => :get, :class => "awesome custom red" %>


    <h3>Ερωτήσεις</h3>
    <p>
        Στατιστικά:  </p>
        <p>
        <%=pluralize(@num_published, "Δημοσιευμένη ερώτηση")%>, <%= link_to pluralize(@num_state4, "Προτεινόμενη ερώτηση"), questions_admin_index_path + '?state=4' %>,
        <%= link_to pluralize(@num_state3, "Ολοκληρωμένη ερώτηση"), questions_admin_index_path + '?state=3' %>, </p>
        <p>
        <%= link_to pluralize(@num_state2, "Μη αποδεκτή ερώτηση"), questions_admin_index_path + '?state=2' %>,
        <%= link_to pluralize(@num_state1, "Ερώτηση προς υποβολή"), questions_admin_index_path + '?state=1' %>,
        <%= link_to pluralize(@num_state0, "Πρόχειρη ερώτηση"), questions_admin_index_path + '?state=0' %>
        </p>
        <p>
        <% if @num_state1 > 0 %>
            <b>Συνολικά <%= link_to pluralize(@num_state1, "Ερώτηση προς υποβολή") , questions_admin_index_path + '?state=1' %> είναι σε κατάσταση αναμονής για έγκριση!</b>
        <% end %>
    </p>


    <% if (admin_signed_in and current_user.id == 1) %>
    <h3>Χρήστες</h3>
    <p>
        Στατιστικά:  </p>

         <p>
        <%=pluralize(@num_users, "χρήστης")%>, <%= link_to pluralize(@num_user_kind0, "Φοιτητής"), users_admin_index_path + '?user_kind=0' %>,
        <%= link_to pluralize(@num_user_kind1, "Καθηγητής"), users_admin_index_path + '?user_kind=1' %>
        </p>

        <p>
        Σύνολο: <%=pluralize(@num_users, "Φοιτητής") %>, <%= pluralize(@num_users_active30days, "Φοιτητής χρησιμοποίησε") %> τον χώρο συζήτησης και επικοινωνίας τις τελευταίες 30 ημέρες.</p>

        <p>Νέοι φοιτητές: <%= pluralize(@num_users_created30days, "Φοιτητής έχει") %> εγγραφεί τις τελευταίες 30 ημέρες στον χώρο συζήτησης και επικοινωνίας.
    </p>
    <% else %>
        <h3>Φοιτητές</h3>
    <p>
        Στατιστικά:  </p>
        <p>
        Σύνολο: <%=pluralize(@num_users, "Φοιτητής") %>, <%= pluralize(@num_users_active30days, "Φοιτητής χρησιμοποίησε") %> τον χώρο συζήτησης και επικοινωνίας τις τελευταίες 30 ημέρες.</p>

        <p>Νέοι φοιτητές: <%= pluralize(@num_users_created30days, "Φοιτητής έχει") %> εγγραφεί τις τελευταίες 30 ημέρες στον χώρο συζήτησης και επικοινωνίας.
    </p>

    <% end %>






    </section>

app/views/admin/questions.html.erb
<section id = "admin">
<%= javascript_include_tag :defaults %>
<h2>Διαχειριστής: <%= @state_name.capitalize %> Ερώτηση</h2>

    <% @questions.each do |question| %>
      <p>
        <h4><%= link_to question.title, question %></h4>
        Δημιουργός: <%= question.user.fullname %>

        <%= link_to 'Διαγραφή', question, :confirm => 'Προσοχή! Αυτή η ενέργεια θα διαγράψει οριστικά την ερώτηση. Να γίνει η διαγραφή;', :method => :delete %>

        <% if question.state == 1 %>
          <%= link_to 'Απόρριψη', editreject_admin_path(question) %>
          <%= link_to 'Όλες οι ερωτήσεις', accept_admin_path(question, :value => '0'), :method => :put %>
          <%= link_to 'Προτεινόμενες ερωτήσεις', accept_admin_path(question, :value => '1'), :method => :put %>
        <% end %>
      </p>
    <% end %>
</section>

app/views/admin/show.html.erb
<h2>Ασκήσεις μου</h2>
<ul>
  <% for writing in @user.writings %>
    <li>
      <%=h writing.exercise.etitle %>
      (<%= link_to "remove", writing, :method => :delete %>)
    </li>
  <% end %>
</ul>

<p><%= link_to "Προσθήκη ασκήσεων", users_path %></p>

app/views/admin/users.html.erb
<section id = "admin">
<%= javascript_include_tag :defaults %>
<h2>Διαχειριστής: <%= @user_kind_name.capitalize %> </h2>



    <% @users.each do |user| %>
      <p>
        <h4><%= link_to user.fullname, user %></h4>
          <%= user.email %>
                 Θεματική ενότητα:   <%= user.lesson.name %>


        <% if user.user_kind == 0 %>
          <%= link_to 'Μεταβολή σε καθηγητή', accept1_admin_path(user, :value => '0'), :method => :put %>
        <% else %>
          <%= link_to 'Μεταβολή σε σπουδαστή', accept1_admin_path(user, :value => '1'), :method => :put %>
        <% end %>

      </p>
    <% end %>

     <div class='pagination'>
        <%= will_paginate @users %>
    </div>
</section>