config/routes.rb
Diplomatiki::Application.routes.draw do
  resources :exercises do
      collection do
           get 'myexercises'
      end
  end

	devise_for :users, :controllers => { :registrations => "users/registrations" }

	match '/auth/:provider/callback' => 'services#create'
	match '/auth/twitter', :as => :auth_twitter

	resources :writings

	resources :services, :only => [:index, :create, :destroy]

	resources :admin, :only => [:index, :delete] do
		member do
			get 'editreject'
			put 'reject'
			put 'accept'
			put 'accept1'
		end
		collection do
			get 'questions'
			get 'users'
		end
	end

	resources :users

	resources :questions do
		collection do
			get 'autocomplete_tag_name'
			get 'all'
			get 'myquestions'
			get 'about'
			delete 'destroy'
		end

		member do
			put 'submit'
			get 'postfacebook'
		end

		resources :comments, :only => [:create, :destroy]
		resources :ratings, :only => [:create, :update, :destroy]
	end

	root :to => 'questions#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Diplomatiki</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= javascript_include_tag 'jquery-1.7.2.min.js', 'jquery-ui-1.8.20.custom.min.js', 'autocomplete-rails.js', 'rails.js', 'ui.datepicker-el.js' %>
  <%= stylesheet_link_tag 'jquery-ui-1.8.20.custom.css' %>
  <%= csrf_meta_tag %>
</head>
<body>
   <header id="page_header">
        <nav id="nav_user">
            <ul>
                <% if user_signed_in? %>
                		<% if admin_signed_in %>
                		    <li><%= link_to "Διαχείριση", admin_index_path %></li>
                     <% end %>
                    <li><span id="currentuser"><%= current_user.email %></span></li>
                       &nbsp;
                    <li><%= link_to "Δικτύωση", services_path %></li>
                    <%= request.path == edit_user_registration_path ? raw("<li class='selected'>") : raw("<li>") %>
                    <li><%= link_to "Το προφίλ μου", edit_user_registration_path %></li>
                    <%= request.path == myquestions_questions_path ? raw("<li class='selected'>") : raw("<li>") %>
                    <li><%= link_to "Οι ερωτήσεις μου", myquestions_questions_path %></li>
                    <li><%= link_to "Έξοδος", destroy_user_session_path, :method => 'delete' %></li>
                    
                <% else %>
                    <%= request.path == new_user_registration_path ? raw("<li class='selected'>") : raw("<li>") %>
                    <li><%= link_to "Εγγραφή", new_user_registration_path %></li>
                    <%= request.path == new_user_session_path ? raw("<li class='selected'>") : raw("<li>") %>
                    <li><%= link_to "Είσοδος", new_user_session_path %></li>
                    
                <% end %>
            </ul>
        </nav>
        <div id="page_title">
           <h1>σχολείο <span> μετά </span> το σχολείο </h1>
            <h2><%= link_to (image_tag "facebook_32.png", :size => "32x32"),{},:title=>'Το σχολείο μετά το σχολείο στο Facebook',:target=>'_blank',:href=>'http://www.facebook.com/schooligans' %> <span><%= l(Time.now, :format => :default) %></span> <%= link_to (image_tag "twitter_32.png", :size => "32x32"),{},:title=>'#sxoleio στο Twitter',:target=>'_blank',:href=>'http://www.twitter.com'
 %></h2>
        </div>
    </header>
      <header id="nav_header">
        <nav id="nav_main">
            <ul>
                <%= request.path == root_path ? raw("<li class='selected'>") : raw("<li>") %>
                <li><%= link_to "Προτεινόμενες ερωτήσεις", root_path %></li>
                <%= request.path == all_questions_path ? raw("<li class='selected'>") : raw("<li>") %>
                <li><%= link_to "Όλες οι ερωτήσεις", all_questions_path %></li>
                <%= request.path == writings_path ? raw("<li class='selected'>") : raw("<li>") %>
                <li><%= link_to "Ημερολόγιο", writings_path %></li>
                <li id="listsearch">
                  <%= form_tag all_questions_path, :method => 'get' do %>
                    <%= text_field_tag :search, params[:search] %>
                   <li> <%= submit_tag "Αναζήτηση", :name => nil, :class => "awesome search red" %> </li>
                <%= request.path == exercises_path ? raw("<li class='selected'>") : raw("<li>") %>
                <li><%= link_to "Ασκήσεις", exercises_path %></li>
                  <% end %>
             </li>
            </ul>
        </nav>
    </header>
    <section id="maincontainer">
        <section id="content">
            <section id="flash">
                <% flash.each do |key, value| %>
                    <div class="flash <%= key %>"><%= value %></div>
                <% end %>
            </section>
<%= yield %>
   </section>
        <section id="sidebar">
           <section id="support" class="box">
                <h3>Συζήτηση-Ενημέρωση</h3>
                <h4>Τρόποι συμμετοχής:</h4>
                <ul>
                    <li>Ρώτησε</li>
                    <li>Σχολίασε</li>
                    <li>Αξιολόγησε</li>
                </ul>
            </section>
            <section id="links" class="box">
                <h3>Χρήσιμα links</h3>
                <li><div><%= link_to "Tag Cloud", "http://users.sch.gr/papetridis/tag-cloud/TagCloudFX.swf" %></div></li>
                <li><div><%= link_to "Security Lab", "http://esecuritylab.blogspot.gr/" %></div></li>
                <li><div><%= link_to "Online Moodle", "http://users.sch.gr/papetridis/moodle/" %></div></li>
                <li><div><%= link_to "Ψηφιακό Σχολείο", "http://www.study4exams.gr/" %></div></li>
                <li><div><%= link_to "Ηλεκτρονική Τάξη", "http://eclass.sch.gr/index.php" %></div></li>
               



            </section>

<a class="twitter-timeline" data-dnt="true" href="https://twitter.com/search?q=%23sxoleio" data-widget-id="456425000036089856">Tweets about "#sxoleio"</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>




				
				



	
            </section>
          
    </section>
    <footer id="page_footer">
        <hr />
        <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/">
            <img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by-nc-sa/3.0/88x31.png" />
        </a>
        <br />
        Το περιεχόμενο είναι διαθέσιμο σύμφωνα με την
        <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/">
            Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License
        </a>.
    </footer>
</body>
</html>